// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://louokabwxvfbempnztzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvdW9rYWJ3eHZmYmVtcG56dHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MjY2ODUsImV4cCI6MjA1ODUwMjY4NX0.k0FABjg4ms2n6j2ZhAI1GaDWX5qaFPwC7hLeqeA3MbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);